Add handling string.match(regex)
allegro/json-logic-kmp pull request #117
Opened 2023-03-01 14:54 UTC by IzabelaSobczyk

## What:
Add handling "string match regex"

## Why:
I need it for user data form (auction modal - for one of error after bid action we have to show this form). I have to validate text from each textInput. I need to check for example if in phone number someone typed "abc defg" instead of "121 121 121" or for name "sun123" instead of "John"

2023-03-02 06:53 UTC, KTGypsy submitted a review, later dismissed

2023-03-07 13:19 UTC, KTGypsy commented on operations-stdlib/src/commonMain/kotlin/string/Match.kt
> +    private fun MatchArguments.invokeRegex() = if (regexOptions.isNullOrEmpty()) matchBasic(regexPattern, text)
using curly brackets would make it more readable when the line is broken

2023-03-07 13:20 UTC, KTGypsy commented on operations-stdlib/src/commonMain/kotlin/string/Match.kt
> +
empty line

2023-03-07 13:20 UTC, lsolniczek approved these changes

2023-03-07 13:21 UTC, KTGypsy requested changes

2023-03-07 13:27 UTC, IzabelaSobczyk commented on operations-stdlib/src/commonMain/kotlin/string/Match.kt
> +    override fun evaluateLogic(expression: Any?, data: Any?): Any? =
Changes added

2023-03-07 13:27 UTC, IzabelaSobczyk commented on operations-stdlib/src/commonMain/kotlin/string/Match.kt
> +
Changes added

2023-03-07 13:35 UTC, KTGypsy approved these changes

2023-03-07 14:01 UTC, pavlo-davydiuk approved these changes

2023-03-07 14:53 UTC, merged