Array operations pt1
allegro/json-logic-kmp pull request #29
Opened 2022-03-03 12:35 UTC by KTGypsy

## What:

* Implementation of map, reduce & filter operations.

## Why:

* To extend operations sets and complete the fundaments of our engine.

## Example:

* https://jsonlogic.com/operations.html#map-reduce-and-filter

2022-03-04 15:15 UTC, PaulinaSadowskaAllegro requested changes

2022-03-04 15:15 UTC, PaulinaSadowskaAllegro commented on src/commonTest/kotlin/operations/array/ReduceTest.kt
> +class ReduceTest : FunSpec({
also when in the registry is some value that cannot be parsed to double

2022-03-07 07:12 UTC, KTGypsy commented on src/commonMain/kotlin/CommonJsonLogicEngine.kt
> +        operations.array.Map.operation,
It conflicts with map as collection usage so i write it like this. Do you have any any idea other than type aliasing?

2022-03-07 07:13 UTC, KTGypsy commented on src/commonMain/kotlin/operations/array/unwrap/EvaluatingUnwrapStrategy.kt
> +        isExpression(this) -> evaluate(this as Map<String, Any?>, data)
isExpression() function is meant to check it

2022-03-07 11:52 UTC, KTGypsy commented on src/commonMain/kotlin/operations/array/unwrap/EvaluatingUnwrapStrategy.kt
> +    fun evaluate(expression: Map<String, Any?>, data: Any?) = JsonLogicEngine.instance.evaluate(expression, data)
I extracted evaluation logic 👍🏽

2022-03-08 07:33 UTC, PaulinaSadowskaAllegro submitted a review, later dismissed

2022-03-08 07:33 UTC, PaulinaSadowskaAllegro commented on src/commonMain/kotlin/JsonLogicEngine.kt
> +            operations.array.Map.operation,
missing import

2022-03-08 14:25 UTC, mkrogulskiallegro2 approved these changes

2022-03-09 06:26 UTC, merged